### ISSUE TITLE
Patched?

### ISSUE THREAD

**Issue by St47b0und** [LionsRH555/NoMoreSecurlyClassroom#2]
securly still blocks sites???

**Comment by LionsRH555** [comment]
it doesnt bypass securly, only securly classroom. use https://geo.mathematicsblogs.online/blog1.html

**Comment by SuperMarioYAHOOYAHOO** [comment]
> it doesnt bypass securly, only securly classroom. use https://geo.mathematicsblogs.online/blog1.html

for me, even two years later it can bypass securely for one page sites
